### ISSUE TITLE
Simpler examples of how to use

### ISSUE THREAD

**Issue by xypd** [cjroehrig/nvtool#3]
Hello @cjroehrig, I'm trying to use your tool and I'm finding it hard to understand how to use it.

you have this as an example, 
`nvtool.py [-h] [-d] [-o <otype>] [-C] [-S] [-R <r>] [-T <r>] [-V <vers>] [-Z] [-D <file>] [-O <file>] [-F <file>] [-I] [infile] [outfile]`

Maybe having an example that is real world ... like what I need, parsing from .cfg to rml text file.

I tried this
$ python nvtool.py -o rml -R FreshTomato.cfg -T FreshTomato.cfg.rml
  File "nvtool.py", line 64
    print(fmt % args, end='')
                         ^
SyntaxError: invalid syntax

Thank you for a cool utility, hopefully you can help me figure out how to use it.

Thanks for any help.

**Comment by cjroehrig** [comment]
I've added some basic usage to the README.      You probably shouldn't use the -R or -T options; they were intended for conversion between different router OSes (e.g. freshtomato-2020.8 to freshtomato-2021.3) and will probably never be finished or complete except for the exact router versions explicitly listed.    

If you stick to the .expq format you'll get a human-readable version that should work with any router version (it doesn't try to unpack or interpret any values).

**Comment by xypd** [comment]
Thanks, will give it try when I get back to my router.

Haha, of course it's a simple solution.

**Comment by xypd** [comment]
Worked like a charm! Thanks @cjroehrig.
